### ISSUE TITLE
Use openvtx without Smart audio wire?

### ISSUE THREAD

**Issue by s2kaka** [OpenVTx/OpenVTx#22]
My FC only have 2 uart for rclink and gps. 
How can i use openvtx without audio wire.
i want max power level when power it on .  
or (wiring SA to an uart, set chanel, power then unplug SA wire from uart to use) will them keep the setting?

**Comment by JyeSmith** [comment]
At they moment a tlm connection is required.  The vtx is currently dumb and doesn't remember any settings.

You can use softserial.

**Comment by s2kaka** [comment]
so what is it default setting now? which power level and channel?
Will it be possible in future?

**Comment by JyeSmith** [comment]
Yes it's possible on the future.

Default is 4uW (pitmode) and a out of range frequency of 5000MHz.

**Comment by s2kaka** [comment]
thanks! i ll wait for it, i have 3 noxe v1 that use inav, can not use softserial because it same TX2 pad that use for rc link.
and i have bough 5 open vtx

**Comment by s2kaka** [comment]
Can i revert to stock FW to use 200mw without smart audio wire?

**Comment by JyeSmith** [comment]
@s2kaka eeprom is merged and you can now setup with SA and it will boot back to the previous settings.
