### ISSUE TITLE
Overheat protection

### ISSUE THREAD

**Issue by longxk** [OpenVTx/OpenVTx#31]
e7082VM's factory firmware has overheat protection.
when temperature is too high, output power decreases automatically.
does openvtx firmware have this feature?

**Comment by JyeSmith** [comment]
No one has added that feature.

Personally I don't like the idea.  I do not want a vtx to potentially start lowering output power mid flight and loose a craft.

**Comment by longxk** [comment]
@JyeSmith Will the vtx fried if powered up with 500mw output on the bench?

**Comment by JyeSmith** [comment]
I have tested this with the EWRF and it was ok.  Doesn't mean that another will be ok.
