### ISSUE TITLE
About my vtx's Migration issues

### ISSUE THREAD

**Issue by HanBingze123** [OpenVTx/OpenVTx#55]
Hello,I made a vtx from RTC6705 and RFPA5542.
Can you tell me how to control power with RFPA5542? 
I appreciate your reply.

**Comment by JyeSmith** [comment]
Its done via PWM to control the voltage bias applied to the RTC6705 output.

**Comment by HanBingze123** [comment]
Thank you!
Do you know which pin of RTC6705 is connect to RFPA5542's
power control pin?
RFPA5542 has three vcc pins，Is it through them to control power?
And PFPA5542 has a "PDET" pin,Is it a output pin or a input pin?
Thanks.

**Comment by JyeSmith** [comment]
I started a design but never finished, built or tested it.  This should give you some ideas.

https://oshwlab.com/jyesmith/openvtx-rfpa5542

**Comment by HanBingze123** [comment]
I saw it.
I is useful for my board.
But I still have some questions...
1.Power control is in RTC6705 or RFPA5542?
2.I saw your PWM controlled voltage,but it connect with a Connector?(I guess it is a ESP32 board)
3.If power control is in RFPA5542,Which pin controls it？
Thanks

**Comment by HanBingze123** [comment]
I' sorry,are you right here?
