### ISSUE TITLE
Add OSD feature with SPI-MAX7456 support, compatible with DJI connector

### ISSUE THREAD

**Issue by lida2003** [OpenVTx/OpenVTx#74]
Hardware: add SPI-MAX7456 chip for OSD function
Firmware: add extra OSD layer for video (Maybe more function, such as OSD on/off, save OSD info to tf???)
UART Interface: pull data from MSP ports

![图片](https://github.com/OpenVTx/OpenVTx/assets/1296171/5426059e-1c0e-4d10-8a8e-623b20edc204)

**Comment by JyeSmith** [comment]
No, just use a FC.
